network:
  name: projectionNet
  num_classes: '@{dataset.num_classes}'
  pretrained: False          # set 'True' to load pretrained model
  checkpoint: none           # ignore if pretrained is false
  num_gpus: '@{num_gpus}'

  # network used for feature extraction
  backbone:
    name: resnet18_32x32
    num_classes: '@{dataset.num_classes}'
    image_size: '@{dataset.image_size}'
    pretrained: True
    checkpoint: 'results/checkpoints/cifar100_res18_acc78.20.ckpt'
    num_gpus: '@{num_gpus}'
