ood_dataset:
  name: cifar100_ood
  num_classes: 100
  
  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  dataset_class: ImglistDataset
  batch_size: 128
  shuffle: False

  split_names: [val, nearood, farood,adv]
  val:
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/cifar100/val_cifar10.txt
  nearood:
    datasets: [cifar10, tin]
    cifar10:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar100/test_cifar10.txt
    tin:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar100/test_tin.txt
  farood:
    datasets: [mnist, svhn, texture, places365]
    mnist:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar100/test_mnist.txt
    svhn:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar100/test_svhn.txt
    texture:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar100/test_texture.txt
    places365:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/cifar100/test_places365.txt
  adv:
    datasets: [fgsm_0.01, fgsm_0.03, fgsm_0.09, fgsm_0.27, pgd_0.01, pgd_0.03, pgd_0.09, pgd_0.27]
    fgsm_0.01:
      data_dir: ./data/images_classic/cifar100/fgsm_0.01/
      imglist_pth: ./data/benchmark_imglist/cifar100/adv.txt
    fgsm_0.03:
      data_dir: ./data/images_classic/cifar100/fgsm_0.03/
      imglist_pth: ./data/benchmark_imglist/cifar100/adv.txt
    fgsm_0.09:
      data_dir: ./data/images_classic/cifar100/fgsm_0.09/
      imglist_pth: ./data/benchmark_imglist/cifar100/adv.txt
    fgsm_0.27:
      data_dir: ./data/images_classic/cifar100/fgsm_0.27/
      imglist_pth: ./data/benchmark_imglist/cifar100/adv.txt
    pgd_0.01:
      data_dir: ./data/images_classic/cifar100/pgd_0.01/
      imglist_pth: ./data/benchmark_imglist/cifar100/adv.txt
    pgd_0.03:
      data_dir: ./data/images_classic/cifar100/pgd_0.03/
      imglist_pth: ./data/benchmark_imglist/cifar100/adv.txt
    pgd_0.09:
      data_dir: ./data/images_classic/cifar100/pgd_0.09/
      imglist_pth: ./data/benchmark_imglist/cifar100/adv.txt
    pgd_0.27:
      data_dir: ./data/images_classic/cifar100/pgd_0.27/
      imglist_pth: ./data/benchmark_imglist/cifar100/adv.txt
